# Generated by Django 5.2 on 2025-05-02 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', '收入'), ('expense', '支出')], max_length=10, verbose_name='类型')),
                ('category', models.CharField(choices=[('sale', '销售'), ('purchase', '采购'), ('salary', '工资'), ('rent', '租金'), ('utility', '水电'), ('other', '其他')], max_length=10, verbose_name='类别')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
            ],
            options={
                'verbose_name': '财务记录',
                'verbose_name_plural': '财务记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
