# Generated by Django 5.2 on 2025-05-03 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='financial',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
