# Generated by Django 5.2 on 2025-05-04 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0005_sale'),
        ('sales', '0002_delete_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('customer', models.CharField(max_length=100, verbose_name='客户')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='销售日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.book', verbose_name='图书')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='销售员')),
            ],
            options={
                'verbose_name': '销售记录',
                'verbose_name_plural': '销售记录',
                'ordering': ['-sale_date'],
            },
        ),
    ]
