# Generated by Django 5.2 on 2025-05-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_options_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('staff', '员工'), ('user', '普通用户')], default='user', max_length=20, verbose_name='角色'),
        ),
    ]
