# Generated by Django 5.2 on 2025-05-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', '收入'), ('expense', '支出')], max_length=20),
        ),
    ]
