# Generated by Django 5.2 on 2025-05-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_financialtransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', '待付款'), ('paid', '已付款')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('completed', '已完成'), ('returned', '已退货')], default='completed', max_length=50),
        ),
    ]
